[RFR] Travis: disable Python 3.7 due to pickle problem in working_set deepcopy
Traceback (most recent call last):
  File "/home/travis/build/OCA/oca.recipe.odoo/anybox/recipe/odoo/tests/test_extract.py", line 176, in test_extract_downloads_to
    self.fill_working_set(fictive=True)
  File "/home/travis/build/OCA/oca.recipe.odoo/anybox/recipe/odoo/testing.py", line 225, in fill_working_set
    self.recipe.install_requirements()  # to get 'ws' attribute
  File "/home/travis/build/OCA/oca.recipe.odoo/anybox/recipe/odoo/base.py", line 619, in install_requirements
    eggs_recipe.install()
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 174, in _working_set
    return copy.deepcopy(cache_storage[cache_key])
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle zipimport.zipimporter objects