[FIX] Tests: pin maxminddb to prevent a dependency on a very recent setuptools
 Version and requirements information containing setuptools:
  Requirement of gevent==21.8.0: setuptools
  Requirement of oca.recipe.odoo: setuptools
  Requirement of gevent: setuptools
  Requirement of zope.interface: setuptools
  Requirement of zope.event: setuptools
  Requirement of maxminddb>=1.4.0: setuptools>=68.2.2
  Requirement of zc.buildout>=2.2.0: setuptools>=8.0
  Requirement of zc.recipe.egg: setuptools
While:
  Installing odoo.
Error: There is a version conflict.
We already have: setuptools 65.5.0
but maxminddb 2.5.1 requires 'setuptools>=68.2.2'.
Error: Process completed with exit code 1.